config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :notification_requests
  post '/notification_requests/:id/send', to: 'notification_requests#send_notification', as: 'send_notification_request'
  post '/notification_requests/:id/resend', to: 'notification_requests#resend_notification', as: 'resend_notification_request'
  resources :notification_registrations
  resources :resources
  resources :suggestions
  resources :sites do
    resources :calendars
  end

  get '/dashboards/sites', to: 'aggregates#sites_status'
  get '/dashboards/hours', to: 'aggregates#user_hours'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'sites#index'

  # Static Pages
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'

  # User Handling
  resources :users do
    resources :work_logs
    put '/certifications/:id', to: 'certification_grants#create'
    delete '/certifications/:id', to: 'certification_grants#destroy'
  end
  post '/certifications/', to: 'certifications#create'
  put '/certifications/:id', to: 'certifications#update'
  delete '/certifications/:id', to: 'certifications#destroy'
  get '/certifications/', to: 'certifications#index'

  get '/signup', to: 'users#new', as: :register
  post '/signup',  to: 'users#create'
  
  get '/login',    to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/organizations', to: 'organizations#index'
  get '/organizations/:organization_id/sites', to: 'sites#index'
  post '/organizations', to: 'organizations#create'
  delete '/organizations/:id', to: 'organizations#destroy'
  put '/organizations/:id', to: 'organizations#update'

  # These methods are for aggregating data into a single view, intended for driving a single UI screen on the app
end

app/models/user.rb
class User < ApplicationRecord
  has_many :role_grants
  has_many :roles, through: :role_grants
  has_many :certification_grants
  has_many :certifications, through: :certification_grants

  has_many :work_logs
  after_create :email_notify_admins
  before_save :register_notification_updates
  belongs_to :organization

  after_initialize do
    self.subscribe_mobile = false if self.subscribe_mobile.nil?
  end

  # has_many :preferred_sites, :class_name => 'Site', :through => :preferred_sites
  has_and_belongs_to_many :preferred_sites, class_name: 'Site', join_table: 'preferred_sites'
  has_and_belongs_to_many :sites_coordinated, class_name: 'Site', join_table: 'users_sites'

  before_save do
    # By default, users should get the NewUser role, which restricts them from
    # modifying anything until an Admin approves them.
    if self.roles.empty?
      self.roles = [Role.find_by(name: 'Volunteer')]
    end
  end

  before_validation do
    self.email = email.downcase.strip

    # By default, users get no certification level
    self.certification ||= 'None'

    # Normalize the submitted phone number
    unless self.phone.nil?
      tmp = self.phone.gsub(/[^\d]/, '')
      self.phone = "#{tmp[0..2]}-#{tmp[3..5]}-#{tmp[6..-1]}"
    end


    self.military_certification = false if self.military_certification.nil?
    self.hsa_certification = false if self.hsa_certification.nil?
    self.international_certification = false if self.international_certification.nil?
  end

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email,
            presence: true,
            length: {maximum: 255},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false}

  has_secure_password
  validates :password,
            presence: true,
            length: { minimum: 6 },
            on: :create

  VALID_CERTIFICATION_LEVELS = %w[None Greeter Basic Advanced SiteCoordinator].freeze
  validates :certification, inclusion: {
    in: VALID_CERTIFICATION_LEVELS,
    message: '%{value} is not a valid certification level'
  }

  VALID_PHONE_REGEX = /\A\d{3}-\d{3}-\d{4}\z/
  validates :phone,
            format: {
              with: VALID_PHONE_REGEX,
              message: 'The phone number must have 10 digits.',
            },
            allow_blank: true


  # Returns the hash digest of the given string.
  def self.digest(s)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(s, cost: cost)
  end

  # Role queries
  def is_admin?
    roles.each do |role|
      return true if role.name == 'Admin'
    end

    # Role not found for user
    false
  end

  # Check whether a user has any of the specified role names.
  # Can be either a single role name, or an array of many. If any in the set of
  # requested roles match any of the user's role set, return true.
  def has_role?(role_name)
    role_name = [role_name] unless role_name.kind_of?(Array)
    roles.each do |role|
      return true if role_name.include?(role.name)
    end

    # None of the requested roles found for user
    false
  end

  def has_admin?(organization_id)
    has_role?('SuperAdmin') || (self.organization_id == organization_id && has_role?(['Admin']))
  end

  def suggestions
    Suggestion.where(user_id: self.id)
  end

  def self.with_role(role_name)
    role = Role.find_by(name: role_name)

    return [] if role.nil?
    grants = RoleGrant.where(role_id: role.id)
    return [] if grants.empty?

    User.where(id: grants.collect(&:user_id))
  end

  def email_notify_admins
    # notify admins via email
    admins = User.with_role('Admin')
    admins.each do |admin|
      begin
        SesMailer.new_user_email(recipient: admin, new_user: self).deliver
      rescue Net::SMTPFatalError => e
        logger.error "Failed to send email to #{admin.email}: #{e}"
        next
      end
    end
  end

  def register_mobile_subscription(device)
    return false if device.nil?

    sns = Rails.configuration.sns
    if self.subscribe_mobile
      protocol = case device.platform
                    when 'sms'
                      'sms'
                    else
                      'application'
                    end

      # Now we register that endpoint set as a subscription on the mobile-updates topic
      subscription = sns.subscribe({
                                       topic_arn: "arn:aws:sns:us-west-2:813809418199:vs-#{Rails.env}-#{self.organization.slug}-sites-mobile",
                                       protocol: protocol,
                                       endpoint: device.endpoint,
                                   })
      logger.info("SNS subscription: #{subscription}")
      self.mobile_subscription_arn = subscription.subscription_arn
    else
      # Unsubscribe from updates on mobile sites
      unless self.mobile_subscription_arn.nil?
        sns.unsubscribe(subscription_arn: self.mobile_subscription_arn)
        self.mobile_subscription_arn = nil
      end
    end
  end

  def register_notification_updates
    new_registration = if self.sms_optin
                     NotificationRegistration.where(user_id: self.id, platform: 'sms').last
                   else
                     NotificationRegistration.where(user_id: self.id, platform: %w(android ios)).last
                       end

    logger.error("No devices registered.") if new_registration.nil?

    if self.sms_optin_changed?
      if new_registration.nil?
        logger.debug "Create a device registration for the user's mobile phone #{self.phone}"
        new_registration = NotificationRegistration.new(user_id: self.id, platform: 'sms', endpoint: self.phone)
        new_registration.save
      end

      # remove all other subscriptions so that this user can use the new one
      NotificationRegistration.where(user_id: self.id).each do |device|
        next if device.id == new_registration.id
        logger.debug("Deleting old device registration: #{device}")
        device.delete
      end

      register_mobile_subscription(new_registration)

      # Re-register notifications for all subscribed sites and roles
      logger.debug("Registering new device for this user")
      new_registration.register_sns
    elsif self.subscribe_mobile_changed?
      register_mobile_subscription(new_registration)
    end
  end
end


app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title, 'Update User Settings') %>
<h1>User Edit</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :phone %>
      <%= f.telephone_field :phone, class: 'form-control' %>

      <%= f.label :certification %>
      <%= f.select :certification,
            options_for_select(
              User::VALID_CERTIFICATION_LEVELS,
              @user.certification
        )
      %>

    <% if current_user == @user %>
        <h3> Password Reset </h3>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    <% end %>
    
      <% if is_admin? %>
        <h3> Update Role Grants </h3>
        <p>(hold down the Ctrl key while clicking to select or deselect roles)</p>
        <%= select_tag "role_ids[]", 
                options_from_collection_for_select(
                    Role.all,
                    "id",
                    "name",
                    selected: RoleGrant.where(:user_id => @user.id).collect {|grant| grant.role_id}
                ),
                {
                    multiple: true,
                    size: Role::VALID_ROLE_NAMES.length
                }
        %>
      <% end %>
      <%= f.submit "Update account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Certification</th>
      <th>Roles</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= user.certification %></td>
        <td><%= user.roles.collect {|r| r.name }.join(', ') %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Site', new_site_path %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: register_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.hidden_field :subscribe_mobile, value: false %>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, 'User Profile') %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>User Profile</h1>
      <p>Name: <%= @user.name %></p>
      <p>Email: <%= @user.email %></p>
      <p>Phone: <%= @user.phone %></p>
      <p>Certification Level: <%= @user.certification %> </p>
      <p>Roles: <%= @user.roles.collect {|r| r.name }.join(', ') %></p>
    </section>
  </aside>
</div>

<div class="signups">
  <h2>Site Work Log</h2>
  <table>
    <tr>
      <th>Site</th>
      <th>Date</th>
      <th>Hours</th>
      <th>Approved</th>
    </tr>
    <% @user.work_logs.find_each do |work_log| %>
      <tr>
        <td><%= link_to work_log.site.name, site_path(work_log.site.slug) %></td>
        <td><%= work_log.date %></td>
        <td><%= work_log.hours %></td>
        <td><%= work_log.approved %></td>
      </tr>
    <% end %>
  </table>

  <h2>Suggestions Submitted</h2>
  <table>
    <tr>
      <th>Subject</th>
      <th>Text</th>
      <th>From Public?</th>
      <th>Status</th>
    </tr>
    <% @user.suggestions.each do |suggestion| %>
      <tr>
        <td><%= link_to suggestion.subject, suggestion_path(suggestion) %></td>
        <td><%= suggestion.details %></td>
        <td><%= suggestion.from_public %></td>
        <td><%= suggestion.status %></td>
      </tr>
    <% end %>
  </table>
</div>