config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :notification_requests
  post '/notification_requests/:id/send', to: 'notification_requests#send_notification', as: 'send_notification_request'
  post '/notification_requests/:id/resend', to: 'notification_requests#resend_notification', as: 'resend_notification_request'
  resources :notification_registrations
  resources :resources
  resources :suggestions
  resources :sites do
    resources :calendars
  end

  get '/dashboards/sites', to: 'aggregates#sites_status'
  get '/dashboards/hours', to: 'aggregates#user_hours'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'sites#index'

  # Static Pages
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'

  # User Handling
  resources :users do
    resources :work_logs
    put '/certifications/:id', to: 'certification_grants#create'
    delete '/certifications/:id', to: 'certification_grants#destroy'
  end
  post '/certifications/', to: 'certifications#create'
  put '/certifications/:id', to: 'certifications#update'
  delete '/certifications/:id', to: 'certifications#destroy'
  get '/certifications/', to: 'certifications#index'

  get '/signup', to: 'users#new', as: :register
  post '/signup',  to: 'users#create'
  
  get '/login',    to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/organizations', to: 'organizations#index'
  get '/organizations/:organization_id/sites', to: 'sites#index'
  post '/organizations', to: 'organizations#create'
  delete '/organizations/:id', to: 'organizations#destroy'
  put '/organizations/:id', to: 'organizations#update'

  # These methods are for aggregating data into a single view, intended for driving a single UI screen on the app
end

app/models/notification_request.rb
class NotificationRequest < ApplicationRecord
  belongs_to :organization

    VALID_AUDIENCES = %w{ volunteers sc }
    validates :audience, presence: true, format: { with: /\A(volunteers|sc|role-.*)\Z/, message: "%{value} is not a valid audience. Must be one of 'volunteers, 'sc', and 'role-$rolename'"}

    def send_broadcast
        unless self.sent.nil?
            return false
        end

        begin
          sns = Rails.configuration.sns
          message = {
            :default => self.message,
            :aps => { :alert => self.message },
            :gcm => {
              :notification => {
                :text => self.message,
#                    :click_action => "A_ViewNotification" 
              }
            }.to_json
          }.to_json
          topic_arn = case self.audience.to_s.downcase
                      when 'volunteers'
                        self.organization.volunteers_topic_arn
                      when 'sc'
                        self.organization.site_coordinators_topic_arn
                      when /role-/
                        role_name = self.audience.to_s.split('-')[1].downcase
                        self.organization.role_topic_arn(role_name)
                      else
                        nil
                      end
          logger.debug("Sending message to Topic #{topic_arn}")
          response = sns.publish({
              :topic_arn => topic_arn,
              :message => message,
              :message_structure => 'json'
          })

          if response.message_id
            self.sent = Time.now
            self.message_id = response.message_id
            self.save
            return self.message_id
          else
            logger.error("No message ID in response: #{response}")
          end
        rescue => exception
          logger.error("Failed to send broadcast: #{exception}")
          self.organization.create_sns_topics
          return nil
        end

        logger.error("Failed to send broadcast")
        return false
    end
end

app/controllers/notification_requests_controller.rb
class NotificationRequestsController < ApplicationController
  before_action :set_notification_request, only: [:resend_notification, :send_notification, :show, :edit, :update, :destroy]
  before_action :check_permissions, only: [:edit, :update, :destroy, :new, :create, :send_notification, :resend]
  skip_before_action :verify_authenticity_token
  wrap_parameters :notification_request, include: [:audience, :message]  

  # GET /notification_requests
  # GET /notification_requests.json
  def index
    @notification_requests = if logged_in?
                               NotificationRequest.where(organization_id: current_user.organization_id)
                             else
                               NotificationRequest.all
                             end
  end

  # GET /notification_requests/1
  # GET /notification_requests/1.json
  def show
  end

  # POST /notification_requests
  # POST /notification_requests.json
  def create
    unless logged_in?
      render json: { errors: 'Not logged in'}, status: :unauthorized
      return
    end
    @notification_request = NotificationRequest.new(notification_request_params)
    @notification_request.organization_id = current_user.organization_id

    if @notification_request.save
      render json: @notification_request, status: :created
    else
      render json: @notification_request.errors, status: :unprocessable_entity
    end
  end

  # POST /notification_requests/1/send
  def send_notification
    unless logged_in?
      render json: { errors: 'Not logged in'}, status: :unauthorized
      return
    end

    resp = @notification_request.send_broadcast
    if resp
      render :show, status: :ok, location: @notification_request 
    else
      render :json => resp, status: 500 
    end
  end

  # POST /notification_requests/1/resend
  def resend_notification
    @notification_request.sent = nil
    @notification_request.save

    resp = @notification_request.send_broadcast
    if resp
      render :show, status: :ok, location: @notification_request
    else
      render :json => resp, status: 500 
    end
  end

  # PATCH/PUT /notification_requests/1
  # PATCH/PUT /notification_requests/1.json
  def update
    unless logged_in? && current_user.has_admin?(@notification_request.organization_id)
      render json: { errors: 'Must be org admin to update notification requests' }, status: :unauthorized
      return
    end

    if @notification_request.update(notification_request_params)
      render :show, status: :ok, location: @notification_request
    else
      render json: @notification_request.errors, status: :unprocessable_entity
    end
  end

  # DELETE /notification_requests/1
  # DELETE /notification_requests/1.json
  def destroy
    @notification_request.destroy
      head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def check_permissions
      unless logged_in? && current_user.has_role?(['Admin'])
        render :json => {:errors => "Unauthorized"}, :status => :unauthorized 
        return
      end
    end

    def set_notification_request
      @notification_request = NotificationRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_request_params
      params.require(:notification_request).permit(:audience, :message)
    end
end


app/helpers/notification_requests_helper.rb
module NotificationRequestsHelper
end

app/views/notification_requests/_form.html.erb
<%= form_for(notification_request) do |f| %>
  <% if notification_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notification_request.errors.count, "error") %> prohibited this notification_request from being saved:</h2>

      <ul>
      <% notification_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :audience %>
    <%= f.select :audience,
          options_for_select(
            NotificationRequest::VALID_AUDIENCES,
            notification_request.audience
          )
    %>
  </div>

  <div class="field">
    <%= f.label :message %>
    <%= f.text_area :message %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notification_requests/edit.html.erb
<h1>Editing Notification Request</h1>

<%= render 'form', notification_request: @notification_request %>

<%= link_to 'Show', @notification_request %> |
<%= link_to 'Back', notification_requests_path %>

app/views/notification_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notification Requests</h1>

<table>
  <thead>
    <tr>
      <th>Audience</th>
      <th>Message</th>
      <th>Sent</th>
      <% if logged_in? && current_user.is_admin? %>
        <th colspan="4"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @notification_requests.each do |notification_request| %>
      <tr>
        <td><%= notification_request.audience %></td>
        <td><%= notification_request.message %></td>
        <td><%= notification_request.sent %></td>
        <% if logged_in? && current_user.is_admin? %>
          <% if notification_request.sent.nil? %>
            <td><%= link_to 'Send', send_notification_request_path(notification_request), method: :post %></td>
          <% end %>
          <td><%= link_to 'Resend', resend_notification_request_path(notification_request), method: :post %></td>
          <td><%= link_to 'Edit', edit_notification_request_path(notification_request) %></td>
          <td><%= link_to 'Destroy', notification_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification Request', new_notification_request_path %>

app/views/notification_requests/new.html.erb
<h1>New Notification Request</h1>

<%= render 'form', notification_request: @notification_request %>

<%= link_to 'Back', notification_requests_path %>

app/views/notification_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Audience:</strong>
  <%= @notification_request.audience %>
</p>

<p>
  <strong>Message:</strong>
  <%= @notification_request.message %>
</p>

<p>
  <strong>Sent:</strong>
  <%= @notification_request.sent %>
</p>

<%= link_to 'Send', send_notification_request_path(@notification_request), method: 'POST' %> |
<%= link_to 'Edit', edit_notification_request_path(@notification_request) %> |
<%= link_to 'Back', notification_requests_path %>