config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :notification_requests
  post '/notification_requests/:id/send', to: 'notification_requests#send_notification', as: 'send_notification_request'
  post '/notification_requests/:id/resend', to: 'notification_requests#resend_notification', as: 'resend_notification_request'
  resources :notification_registrations
  resources :resources
  resources :suggestions
  resources :sites do
    resources :calendars
  end

  get '/dashboards/sites', to: 'aggregates#sites_status'
  get '/dashboards/hours', to: 'aggregates#user_hours'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'sites#index'

  # Static Pages
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'

  # User Handling
  resources :users do
    resources :work_logs
    put '/certifications/:id', to: 'certification_grants#create'
    delete '/certifications/:id', to: 'certification_grants#destroy'
  end
  post '/certifications/', to: 'certifications#create'
  put '/certifications/:id', to: 'certifications#update'
  delete '/certifications/:id', to: 'certifications#destroy'
  get '/certifications/', to: 'certifications#index'

  get '/signup', to: 'users#new', as: :register
  post '/signup',  to: 'users#create'
  
  get '/login',    to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/organizations', to: 'organizations#index'
  get '/organizations/:organization_id/sites', to: 'sites#index'
  post '/organizations', to: 'organizations#create'
  delete '/organizations/:id', to: 'organizations#destroy'
  put '/organizations/:id', to: 'organizations#update'

  # These methods are for aggregating data into a single view, intended for driving a single UI screen on the app
end

app/models/site.rb
class Site < ApplicationRecord
  has_many :calendars
  has_many :site_features
  has_and_belongs_to_many :coordinators, class_name: 'User', join_table: 'users_sites', touch: true
  has_and_belongs_to_many :preferred, class_name: 'User', join_table: 'preferred_sites', touch: true
  belongs_to :organization

  after_create :create_sns_topic
  after_update :send_preferred_site_notification, :send_mobile_team_notification
  after_destroy :delete_sns_topic


  before_validation :slugify_self
  def slugify_self
    self.slug = (self.slug.nil? || self.slug.to_s.strip.empty?) ? self.name.parameterize : self.slug
  end
  validates :slug, {
    uniqueness: true,
    format: {
      with: /\A[a-z0-9-]+-?(-[a-z0-9-]+)*\z/,
      message: 'Must be a valid URL segment, using lowercase latin characters and single dashes. Leave blank to have a slug auto-generated from your sitename.'
    }
  }

  serialize :monday_open, Tod::TimeOfDay
  serialize :monday_close, Tod::TimeOfDay
  serialize :tuesday_open, Tod::TimeOfDay
  serialize :tuesday_close, Tod::TimeOfDay
  serialize :wednesday_open, Tod::TimeOfDay
  serialize :wednesday_close, Tod::TimeOfDay
  serialize :thursday_open, Tod::TimeOfDay
  serialize :thursday_close, Tod::TimeOfDay
  serialize :friday_open, Tod::TimeOfDay
  serialize :friday_close, Tod::TimeOfDay
  serialize :saturday_open, Tod::TimeOfDay
  serialize :saturday_close, Tod::TimeOfDay
  serialize :sunday_open, Tod::TimeOfDay
  serialize :sunday_close, Tod::TimeOfDay

  def has_feature?(feature)
    self.site_features.each do |site_feature|
      return true if site_feature.feature == feature
    end
    return false
  end

  def work_history(start_date = Date.today - 7, end_date = Date.today - 1)
    dates = (start_date..end_date).collect {|d| d.strftime("%Y-%M-%d")}
    WorkLog.where(site_id: self.id)
  end

  #
  # PUSH NOTIFICATIONS
  #

  # Send updates to anyone who has flagged this as a preferred site
  def send_preferred_site_notification
    topic_arn = self.get_sns_topic
    if topic_arn.blank?
      logger.error "Failed to get or create a topic"
      return
    else
      logger.debug "Site #{self.slug} updated. Sending out push notifications via SNS to Topic #{topic_arn}"
    end

    sns = Rails.configuration.sns
    message = "Site #{self.name} updated"
    response = sns.publish({
        :topic_arn => topic_arn,
        :message => {
            :default => message,
            :aps => {:alert => message},
            :gcm => {:notification => {:text => message}}
        }.to_json,
        :message_structure => 'json',
    })

    logger.debug(response)
    if response.message_id
      logger.info "Update to #{self.slug} -- Sent Push via SNS: MessageID=#{response.message_id}"
    else
      logger.error "Update to #{self.slug} -- No message ID back from SNS"
    end
  end

  # Send updates to the mobile team if this is a mobile site
  def send_mobile_team_notification
    # No-op if this site isn't Mobile
    return true if self.site_features.where(:feature => 'Mobile').count == 0
    
    logger.debug "Site #{self.slug} updated. Sending out push notifications to the Mobile Team via SNS"

    # TODO: lookup mobile team Topic
    topic_arn = "arn:aws:sns:us-west-2:813809418199:vs-#{Rails.env}-#{self.organization.slug}-sites-mobile"

    sns = Rails.configuration.sns
    message = "Mobile Site #{self.name} updated"
    response = sns.publish({
                               :topic_arn => topic_arn,
                               :message => {
                                   :default => message,
                                   :aps => {:alert => message},
                                   :gcm => {:notification => {:text => message}}.to_json,
                               }.to_json,
                               :message_structure => 'json',
                           })

    if response.message_id
      logger.info "Update to #{self.slug} -- Sent Push via SNS: MessageID=#{response.message_id}"
    else
      logger.error "Update to #{self.slug} -- No message ID back from SNS"
    end
  end

  def get_sns_topic
    if self.sns_topic.nil?
      self.create_sns_topic
    else
      self.sns_topic
    end
  end

  def site_updates_sns_topic_name
    "vs-#{Rails.env}-org#{self.organization_id}-site#{self.id}"
  end
  def create_sns_topic
    sns = Rails.configuration.sns
    resp = sns.create_topic({
      name: self.site_updates_sns_topic_name,
    })
    self.sns_topic = resp.topic_arn
    self.save

    self.sns_topic
  end

  def delete_sns_topic
    return true if self.sns_topic.nil?
    sns = Rails.configuration.sns
    sns.delete_topic({
      topic_arn: self.sns_topic
    })
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy]
  before_action :set_eligible_sitecoordinators, only: [ :edit, :new ]
  skip_before_action :verify_authenticity_token

  # GET /sites
  # GET /sites.json
  def index
    filters = {
        :active => true
    }
    if params[:deactivated] == 'true'
      filters.delete(:active)
    end
    if logged_in?
      filters[:organization_id] = current_user.organization_id
    end
    if params.has_key?(:organization_id)
      filters[:organization_id] = params[:organization_id]
    end
    if params.has_key?(:features) && !params[:features].empty?
      featured_sites = SiteFeature.where(:feature => @capabilities)
      filters[:id] = featured_sites.collect {|f| f.site_id}
    end

    @sites = if filters.empty?
               Site.all
             else
               Site.where(filters)
             end
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
  end

  # GET /sites/new
  def new
    @site = Site.new
    respond_to do |format|
      if is_admin?
        format.html { render :new }
        format.json { render json: { :errors => 'This is a web function. No JSON to be provided.'}, :status => 406}
      else
        format.html { render :file => 'public/401', :status => :unauthorized, :layout => false }
        format.json { render json: { :errors => 'Not authorized' }, :status => :unauthorized }
      end
    end
  end

  # GET /sites/1/edit
  def edit

    respond_to do |format|
      if logged_in? && (is_admin? || @site.sitecoordinator == current_user.id)
        format.html { render :edit }
        format.json { render json: { :errors => 'This is a web function. No JSON to be provided.'}, :status => 406}
      else
        format.html { render :file => 'public/401', :status => :unauthorized, :layout => false }
        format.json { render json: { :errors => 'Not authorized' }, :status => :unauthorized }
      end
    end
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params)
    if @site.slug.to_s.strip.empty?
      @site.slug = @site.name.parameterize
    end

    unless logged_in?
      logger.error("Only a logged-in admin can create a site")
      render :json => {:errors => 'Not logged in'}, :status => :unauthorized
      return
    end

    unless current_user.has_role?(['Admin', 'SuperAdmin'])
      logger.error("Only an admin can create a site")
      render :json => {:errors => 'Not an admin'}, :status => :unauthorized
      return
    end
    # SuperAdmins can create resources in any org
    unless current_user.has_role?('SuperAdmin')
      @site.organization = current_user.organization
    end
    
    if @site.save
      @site.site_features = params[:site_features].collect {|f| SiteFeature.create(feature: f)} unless params[:site_features].nil?
      render :show, status: :created, location: @site
    else
      logger.error("Errors: #{@site.errors.to_hash.to_json}")
      # logger.debug("Raw request: #{request.body.read}")

      render json: @site.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    if @site.nil?
      render :json => {:errors => "Invalid ID or slug. Site not found for '#{params[:id]}'"}, :status => :not_found
      return
    end
    unless logged_in?
      render json: {errors: 'Must be logged in to update a site'}, status: :unauthorized
      return
    end
    if current_user.has_admin?(@site.organization_id) || (@site.coordinators.include?(current_user) && current_user.has_role?('SiteCoordinator'))
      @site.site_features = params[:site_features].collect {|f| SiteFeature.create(feature: f)} unless params[:site_features].nil?
      @site.site_features = params[:site_features].collect {|f| SiteFeature.create(feature: f)} unless params[:site_features].nil?

      unless params[:sitecoordinators].nil?
        new_coordinators = params[:sitecoordinators].collect{|x| x[:id]}
        logger.debug("Updating Sitecoordinators list for #{@site.slug}: #{new_coordinators.join(', ')}")
        @site.coordinators = User.where(:id => new_coordinators)
        @site.coordinators.each {|u| u.touch}
        @site.touch
      end

      if @site.update(site_params)
        render :show, status: :ok, location: @site
      else
        render json: @site.errors, status: :unprocessable_entity
      end
    else
      render :json => {:errors => 'Unauthorized'}, :status => :unauthorized
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    # only admins from the same Organization can delete sites
    unless (is_admin? && current_user.organization == @site.organization) || current_user.has_role?('SuperAdmin')
      render :json => { :errors => 'Not authorized'}, :status => :unauthorized
      response.set_header('Content-Type', 'application/json')
      return
    end

    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url, notice: 'Site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = if params[:id] =~ /\A\d+\z/
        Site.find(params[:id])
      else
        Site.find_by(slug: params[:id])
      end

      if @site.nil?
        render :json => {:errors => "Invalid ID or slug. Site not found for '#{params[:id]}'"}, :status => :not_found
        return
      end
    end

    def site_signup_metadata(site_id)
      [ Site.find(site_id).work_history, Site.find(site_id).work_intents ]
    end


    def set_eligible_sitecoordinators
      @eligible_sitecoordinators = User.all.map {|u| u.has_role?('SiteCoordinator') ? [u.name, u.id] : nil}.compact
      @eligible_sitecoordinators = [] unless @eligible_sitecoordinators
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      fields_permitted = [:name, :slug,
          :google_place_id, :street, :city, :state, :zip, :latitude, :longitude,
          :monday_open, :monday_close, :tuesday_open, :tuesday_close,
          :wednesday_open, :wednesday_close, :thursday_open, :thursday_close,
          :friday_open, :friday_close, :saturday_open, :saturday_close,
          :sunday_open, :sunday_close,

          :monday_efilers, :tuesday_efilers, :wednesday_efilers,
          :thursday_efilers, :friday_efilers, :saturday_efilers, :sunday_efilers,

          :site_features,

          :season_start, :season_end,
          :sitecoordinators,
          :contact_name, :contact_phone,
          :notes,
          :active]
      if logged_in? && current_user.has_role?('SuperAdmin')
        fields_permitted |= [:organization_id]
      end
      params.require(:site).permit(fields_permitted)
    end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_form.html.erb
<%= form_for(site) do |f| %>
  <% if site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :slug %>
    <%= f.text_field :slug %>
  </div>

  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>

  <div class="field">
    <%= f.label :google_place_id, 'Google Maps Place ID' %>
    <%= f.text_field :google_place_id %>
  </div>

  <div class="field">
    <%= f.label :street %>
    <%= f.text_field :street %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :zip %>
    <%= f.text_field :zip %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h1>Update Site Settings</h1>

<%= render 'form', site: @site %>

<%= link_to 'Show', site_path(@site.slug) %> |
<%= link_to 'Back', sites_path %>

app/views/sites/index.html.erb
<h1>Sites</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Coordinates</th>
      <th>Place ID</th>
      <th>Site Coordinator</th>
      <th>Backup Coordinator</th>
      <th>Current Status</th>
      <% if is_admin? %>
      <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @sites.each do |site| %>
      <% sc = begin
                (site.sitecoordinator.nil?) ? nil : User.find(site.sitecoordinator) 
              rescue ActiveRecord::RecordNotFound => e
                site.sitecoordinator = nil
                site.save
                nil
              end
      %>
      <% bc = begin
                (site.backup_coordinator_id.nil?) ? nil : User.find(site.backup_coordinator_id) 
              rescue ActiveRecord::RecordNotFound => e
                site.backup_coordinator_id = nil
                site.save
                nil
              end
      %>
      <tr>
        <td><%= link_to site.name, site_url(site.slug) %></td>
        <td><%= site.street %>, <%= site.city %>, <%= site.state %> <%= site.zip %></td>
        <td><%= site.latitude %>, <%= site.longitude %></td>
        <td><%= site.google_place_id %>
        <td><%= (sc.nil?) ? 'None Assigned' : sc.name %></td>
        <td><%= (bc.nil?) ? 'None Assigned' : bc.name %></td>
        <td><%= site.sitestatus %></td>
        <% if is_admin? %>
        <td><%= link_to 'Edit', edit_site_path(site.slug) %></td>
        <td><%= link_to 'Destroy', site_path(site.slug), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Site', new_site_path %>

app/views/sites/new.html.erb
<h1>New Site</h1>

<%= render 'form', site: @site %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @site.name %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @site.slug %>
</p>

<p>
  <strong>Address</strong>
  <%= @site.street %>, <%= @site.city %>, <%= @site.state %> <%= @site.zip %>
</p>

<p>
  <strong>Google Place ID:</strong>
  <%= @site.google_place_id %>
</p>

<p>
  <strong>Coordinates:</strong>
  <%= @site.latitude %>, <%= @site.longitude %>
</p>

<p>
  <strong>Site Coordinators:</strong>
  <ul>
    <% @site.coordinators.each do |sc| %>
    <li><%= sc.name %> (<%= sc.email %>)</li>
    <% end %>
  </ul>

</p>

<p>
  <strong>Current Site Status:</strong>
  <%= @site.sitestatus %>
</p>

<p>
  <strong>Site Features:</strong>
  <% if @site.site_features.empty? %>
  <p>-none-</p>
  <% else %>
    <ul>
    <% @site.site_features.each do |feature| %>
      <li><%= feature.feature %></li>
    <% end %>
    </ul>
  <% end %>

<p>
  <strong>Site Calendar Deviations</strong>
  <table>
    <tr>
      <th>Day</th>
      <th>Open</th>
      <th>Close</th>
      <th>eFilers Needed</th>
    </tr>
    <% @site.calendars.each do |calendar_override| %>
    <tr id="shift-row-<%= calendar_override.id %>" class="shift-row">
      <td><%= calendar_override.date %></td>
      <td><%= calendar_override.open %></td>
      <td><%= calendar_override.close %></td>
      <td><%= calendar_override.efilers_needed %></td>
    </tr>
    <% end %>
  </table>
</p>


<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Back', sites_path %>