config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :notification_requests
  post '/notification_requests/:id/send', to: 'notification_requests#send_notification', as: 'send_notification_request'
  post '/notification_requests/:id/resend', to: 'notification_requests#resend_notification', as: 'resend_notification_request'
  resources :notification_registrations
  resources :resources
  resources :suggestions
  resources :sites do
    resources :calendars
  end

  get '/dashboards/sites', to: 'aggregates#sites_status'
  get '/dashboards/hours', to: 'aggregates#user_hours'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'sites#index'

  # Static Pages
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'

  # User Handling
  resources :users do
    resources :work_logs
    put '/certifications/:id', to: 'certification_grants#create'
    delete '/certifications/:id', to: 'certification_grants#destroy'
  end
  post '/certifications/', to: 'certifications#create'
  put '/certifications/:id', to: 'certifications#update'
  delete '/certifications/:id', to: 'certifications#destroy'
  get '/certifications/', to: 'certifications#index'

  get '/signup', to: 'users#new', as: :register
  post '/signup',  to: 'users#create'
  
  get '/login',    to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/organizations', to: 'organizations#index'
  get '/organizations/:organization_id/sites', to: 'sites#index'
  post '/organizations', to: 'organizations#create'
  delete '/organizations/:id', to: 'organizations#destroy'
  put '/organizations/:id', to: 'organizations#update'

  # These methods are for aggregating data into a single view, intended for driving a single UI screen on the app
end

app/views/layouts/_backoffice_dropdown.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    BackOffice<b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to 'Notifications', notification_requests_path %></li>
    <li><%= link_to 'Suggestions', suggestions_path %></li>
  </ul>
</li>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Find a tax assistance site in San Antonio!
  </small>
  <nav>
      <ul>
        <li><%= link_to 'About', about_path %></li>
        <% if logged_in? %>
          <li><%= link_to I18n.t('feedback'), new_suggestion_path %></li>
        <% else %>
          <li><%= link_to 'Contact Us', contact_path %></li>
        <% end %>
      </ul>
  </nav>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "VITA Site Finder", root_path, id: 'logo' %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <% if logged_in? && is_admin? %>
          <%= render 'layouts/sites_dropdown' %>
        <% else %>
          <li><%= link_to 'Sites', sites_path %></li>
        <% end %>

        <% if logged_in? && is_admin? %>
          <%= render 'layouts/users_dropdown' %>
          <%= render 'layouts/backoffice_dropdown' %>
        <% end %>


        <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Profile', current_user %></li>
                <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to 'Log out', logout_path, method: 'delete' %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to 'Log In', login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_ie_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/_sites_dropdown.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    Sites <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to 'List', sites_path %></li>
    <li><%= link_to 'Create', new_site_path %></li>
  </ul>
</li>

app/views/layouts/_users_dropdown.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    Users <b class="caret"></b>
  </a>
  <ul class="dropdown-menu">
    <li><%= link_to 'List', users_path %></li>
  </ul>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield :title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/ie_shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>